development:
  adapter: postgresql
  database: develop
  pool: 20
  timeout: 5000
  username: brunosapienza
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: brunosapienza
  host: localhost
  min_messages: warning
